app/articles/urls.py
from django.urls import path
from articles import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'articles'
urlpatterns = [
	path('', views.index, name='10-ka Labs'),
	path('new_post/', views.new_post, name='new_post'),
	path('post/<int:post_id>', views.display_single, name='display_single'),
	path('get_posts/', views.get_posts, name='get_posts'),
	path('tags/<int:tag_id>', views.tags_list, name='tags_list'),
	path('ajax/vote/', views.vote, name="vote"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/config/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('labs/', include('labs.urls')),
    path('user/', include('accounts.urls')),
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
]

app/labs/urls.py
from django.urls import path
from labs import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'labs'
urlpatterns = [
    path('new_lab/', views.new_lab, name='new_lab'),
    path('labs_catalog/', views.labs_catalog, name='labs_catalog'),
    path('display_lab/<int:lab_id>', views.display_lab, name='display_lab'),
    path('task_status/<int:user_id>&<str:task_id>', views.task_status, name='task_status'),
    path('download/<str:path>', views.download, name='download')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/articles/models.py
from accounts.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone


class TagManager(models.Manager):
    def add_tags(self, tag):
        if Tag.objects.filter(tag_name=tag).exists():
            tag = self.get(tag_name=tag)
            tag.total += 1
            tag.save(update_fields=['total'])
        else:
            tag = self.create(tag_name=tag)
            tag.save()
        return tag


class Tag(models.Model):
    objects = TagManager()
    tag_name = models.TextField()
    total = models.IntegerField(default=1)

    def __str__(self):
        return self.tag_name


class LikeDislikeManager(models.Manager):
    def create_like_dislike(self, user, instance, object_id, action):
        try:
            like = self.filter(user=user).get(object_id=object_id)
            if like.beenPut and action == 'down':
                like.beenPut = False
                if instance.total_likes >= 1:
                    instance.total_likes -= 1
            elif not like.beenPut and action == 'up':
                like.beenPut = True
                instance.total_likes += 1
            like.save(update_fields=['beenPut'])
        except:
            like = self.create(user=user, obj=instance, object_id=instance.id)
            if action == 'up':
                like.beenPut = True
                instance.total_likes += 1
            like.save()

        instance.save(update_fields=['total_likes'])
        return like


class LikeDislike(models.Model):
    objects = LikeDislikeManager()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    beenPut = models.BooleanField(default=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    obj = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.user


class PostManager(models.Manager):
    def create_post(self, **kwargs):
        tags = kwargs['tags']
        post = self.create(author=kwargs.get('author'),
                           title=kwargs.get('title'), text=kwargs.get('text'),
                           is_pinned=kwargs.get('is_pinned'))
        post.save()
        for tag in tags:
            current_tag = Tag.objects.add_tags(tag)
            post.tags.add(current_tag)
        return post


class Post(models.Model):
    objects = PostManager()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')
    total_comments = models.IntegerField(default=0)
    total_likes = models.IntegerField(default=0)
    is_pinned = models.BooleanField(default=True)

    def publish(self):
        self.create_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class CommentManager(models.Manager):
    def create_comment(self, author, post, text):
        comment = self.create(author=author, post=post, text=text)
        post = Post.objects.get(id=post.id)
        post.total_comments += 1
        post.save(update_fields=['total_comments'])

        return comment


class Comment(models.Model):
    objects = CommentManager()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    total_likes = models.IntegerField(default=0)

    def publish(self):
        self.create_date = timezone.now()
        self.save()

    def __str__(self):
        return self.text

app/articles/forms.py
from django import forms


class PostForm(forms.Form):
    title = forms.CharField(label='Заголовок', max_length=255)
    text = forms.CharField(label='Текст', widget=forms.Textarea(attrs={'rows': '3'}))
    tags = forms.CharField(label="Тэги", required=False, max_length=50)
    pinned = forms.BooleanField(label="Закрепить", required=False)

    def clean_tags(self):
        tags = self.cleaned_data['tags']
        if tags:
            tags.split()
        return tags

    def clean_text(self):
        text = self.cleaned_data['text']
        return text

    def clean_title(self):
        title = self.cleaned_data['title']
        return title

    def clean_pinned(self):
        return self.cleaned_data['pinned']


class CommentForm(forms.Form):
    text = forms.CharField(label='Your comment', widget=forms.Textarea(attrs={'rows': '3'}))

    def clean(self):
        return self.cleaned_data

app/articles/views.py
import json

from articles.forms import PostForm, CommentForm
from articles.models import Post, Comment, Tag, LikeDislike
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404


def index(request: WSGIRequest):
    query_filter = None

    filters = request.GET.keys()
    if len(filters) == 1:
        query_filter = list(filters)[0]
    filter_map = {
        "popular": "-total_comments",
        "pinned": "-is_pinned",
    }

    sort_key = filter_map.get(query_filter, '-create_date')
    if sort_key == '-is_pinned':
        questions_list = Post.objects.all().filter(is_pinned=True).order_by('-create_date')
    else:
        questions_list = Post.objects.all().order_by(sort_key)
    question_context = paginate(questions_list, request, 5)
    question_context.update({'sort_key': sort_key})
    return render(request, 'articles/index.html', context=question_context)


def new_post(request):
    if request.method == 'GET':
        form = PostForm()
        if request.user.is_authenticated:
            return render(request, 'articles/utils/new_post.html', {'form': form})
        return redirect('accounts:login')
    else:
        if not request.user.is_authenticated:
            return HttpResponse(status=403)
        form = PostForm(request.POST)
        if not form.is_valid():
            return redirect(request.META['HTTP_REFERER'])
        tags = form.cleaned_data['tags'].split()
        post_full = Post.objects.create_post(author=request.user, title=form.cleaned_data['title'],
                                             text=form.cleaned_data['text'], is_pinned=form.cleaned_data['pinned'],
                                             tags=tags)
        if post_full:
            post_full.save()
            return redirect('../post/{}'.format(post_full.id))
        else:
            return render(request, 'articles/utils/new_post.html', {'error': 'Something went wrong. Please try again'})


def display_single(request, post_id):
    context = {}
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        form = CommentForm(request.POST)
        if not form.is_valid():
            context.update({'form': form})
        comment_full = Comment.objects.create_comment(author=request.user, post=post,
                                                      text=form.cleaned_data['text'])
        comment_full.save()
        return redirect('../post/{}'.format(post.id))
    comments = Comment.objects.filter(post=post_id).order_by('-create_date')
    comments_context = paginate(comments, request, 3)
    form = CommentForm()
    context.update({'form': form, 'post': post,
                    'page_object': comments_context['page_object'],
                    'is_paginated': comments_context['is_paginated'],
                    'next_url': comments_context['next_url'],
                    'prev_url': comments_context['prev_url']})
    return render(request, 'articles/utils/post.html', context=context)


def tags_list(request, tag_id):
    context = {}
    tag = get_object_or_404(Tag, id=tag_id)
    questions = Tag.objects.filter(id=tag_id)
    context.update({'questions': questions, 'tag': tag})
    return render(request, 'articles/utils/tags.html', context=context)


def paginate(objects_list, request, per_page):
    data_on_page = Paginator(objects_list, per_page)
    page_number = request.GET.get('page', 1)
    page = data_on_page.get_page(page_number)
    is_paginated = page.has_other_pages()
    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''
    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''
    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url,
    }
    return context


@login_required
def vote(request):
    post = request.POST
    user = request.user

    action = post['action']
    data_id = post['data_id']
    data_type = post['data_type']
    if data_type == 'post':
        data_object = Post.objects.get(pk=data_id)
    else:
        data_object = Comment.objects.get(pk=data_id)
    LikeDislike.objects.create_like_dislike(user, instance=data_object, object_id=data_id, action=action)

    return HttpResponse(data_object.total_likes, status=200)


@login_required
def get_posts(request: WSGIRequest):
    search = request.GET.get('search')
    page = request.GET.get('page')
    if search == '':
        return HttpResponse(status=200)
    if len(search) < 3:
        return HttpResponse('слишком короткий запрос (< 3 символов)', status=400)
    res = Post.objects.all().filter(title__icontains=search).order_by('-create_date')
    data = [{"id": res[i].id, "text": res[i].title} for i in range(len(res))]
    return HttpResponse(json.dumps({"results": data}), status=200)

app/articles/templates/articles/utils/answer.html
{% load static %}
<div class="card border-dark mb-3">
    <div class="card-header">
        <div class="row">
            <h3 class="col-2">{{ answer.author }}</h3>
            <p class="col-10 text-right"> {{ answer.create_date }}</p>
        </div>
    </div>
    <div class="card-body text-dark">
        <div class="row">
            <div class="row col-3">
                 {% include 'articles/utils/likeDisAnswers.html' %}
                <div class="row col-7">
                    {% if answer.author.avatar != '' %}
                        <img class="user_avatar card-img" src="{% static answer.author.avatar %}" alt="no avatar">
                    {% else %}
                        <img class="user_avatar card-img" src="{% static 'default_avatar.svg' %}" alt="">
                    {% endif %}
                </div>
            </div>
            <div class="col-9">
                <p class="card-text">{{ answer.text }}</p>
                <div class="form-group form-check text-right">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Correct</label>
                </div>
            </div>
        </div>
    </div>
</div>

app/articles/templates/articles/utils/ask.html
{% extends 'articles/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="text-center new_question my-1">
        <h3 class="font-italic">New question</h3>
    </div>
    <div class="card mt-3">
        <div class="card-body">
            {% if error %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endif %}
            <form method="POST" action="{% url 'articles:ask' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="col ask_btn text-center">
                    <button class="btn btn-success" id="edit" type="submit">ASK</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

app/articles/templates/articles/utils/buffer.html
{% block content %}
    {% load static %}
    <div class="col-4 mt-2 text-center">
        {% if comment %}
            <button type="submit"
                    data-object="comment"
                    data-action="up-vote"
                    data-user="{{ user.id }}"
                    data-id="{{ comment.id }}"
                    class="like btn-xs bg-light rounded">
                <img src="{% static 'images/caret-up.svg' %}" width="20" height="20" alt="">
            </button>
            <strong class="font-italic">
                {% if comment.total_likes == -1 %}
                    0
                {% else %}
                    {{ comment.total_likes }}
                {% endif %}
            </strong>
            <button type="submit"
                    data-object="comment"
                    data-action="down-vote"
                    data-user="{{ user.id }}"
                    data-id="{{ comment.id }}"
                    class="like btn-xs bg-light rounded">
                <img src="{% static 'images/caret-down.svg' %}" width="20" height="20" alt="">
            </button>
        {% else %}
            <button type="submit"
                    data-object="post"
                    data-action="up-vote"
                    data-user="{{ user.id }}"
                    data-id="{{ post.id }}"
                    class="like btn-xs bg-light rounded">
                <img src="{% static 'images/caret-up.svg' %}" width="20" height="20" alt="">
            </button>
            <button type="button" class="btn btn-light" id="vote{{ post.id }}" disabled>
                <strong class="font-italic">
                    {% if post.total_likes == -1 %}
                        kkk
                    {% else %}
                        {{ post.total_likes }}
                    {% endif %}
                </strong>
            </button>
            <button type="submit"
                    data-object="comment"
                    data-action="down-vote"
                    data-user="{{ user.id }}"
                    data-id="{{ post.id }}"
                    class="like btn-xs bg-light rounded">
                <img src="{% static 'images/caret-down.svg' %}" width="20" height="20" alt="">
            </button>
        {% endif %}
    </div>
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous">
</script>
{% block javascript %}
    {% if  user.is_authenticated %}
        <script type="text/javascript" src="{% static "js/LikeDislike.js" %}"></script>
    {% endif %}
{% endblock javascript %}

app/articles/templates/articles/utils/comment.html
{% load static %}
<div class="card border-dark mb-3">
    <div class="card-header">
        <div class="row">
            <h3 class="col-2">{{ comment.author }}</h3>
            <p class="col-10 text-right"> {{ comment.create_date }}</p>
        </div>
    </div>
    <div class="card-body text-dark">
        <div class="row">
            <div class="row col-3">
                 {% include 'articles/utils/likeDisComments.html' %}
                <div class="row col-7">
                    {% if comment.author.avatar != '' %}
                        <img class="user_avatar card-img" src="{{ MEDIA_URL }}{{ comment.author.avatar }}"
                             alt="no avatar">
                    {% else %}
                        <img class="user_avatar card-img" src="{% static 'avatars/default_avatar.svg' %}" alt="">
                    {% endif %}
                </div>
            </div>
            <div class="col-9">
                <p class="card-text">{{ comment.text }}</p>
                <div class="form-group form-check text-right">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Correct</label>
                </div>
            </div>
        </div>
    </div>
</div>

app/articles/templates/articles/utils/lab_card.html
{% load static %}


<div class="card mt-4">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ lab.linked_post.id }}"
                    aria-expanded="false" aria-controls="collapse{{ lab.linked_post.id }}">
                {{ lab.linked_post.title|truncatewords:100 }}
            </button>
        </h5>
    </div>

    <div id="collapse{{ lab.linked_post.id }}" class="collapse show" aria-labelledby="headingOne"
         data-parent="#labs_catalog">
        <div class="card-body">
            <div>
              <span>
              {{ lab.linked_post.text }}
          </span>
            </div>
            <form action='{% url 'articles:display_lab' lab.id %}' method='POST'>
                 {% csrf_token %}
                <button id="lab-load-btn-{{ lab.id }}" type="submit" class="btn btn-dark prepareLab mt-4">Приступить
                </button>
            </form>
        </div>
    </div>
</div>

app/articles/templates/articles/utils/labs_catalog.html
{% extends 'articles/base.html' %}

{% block content %}
<div id="labs_catalog">
    {% if labs %}
        <h3>Список лабораторных работ:</h3>
        {% for lab in labs %}
            {% include 'articles/utils/lab_card.html' %}
        {% endfor %}
    {% else %}
        <h3 class="font-italic">Лабораторные работы не найдены!</h3>
    {% endif %}
</div>
{% endblock %}

app/articles/templates/articles/utils/likeDisAnswers.html
{% block content %}
    {% load static %}
    <div class="col-4 mt-2 text-center">
        <button type="submit"
                data-type="answer"
                data-action="up"
                data-id="{{ answer.id }}"
                class="col newVote btn-xs bg-light rounded">
            <img src="{% static 'images/caret-up.svg' %}" width="20" height="20" alt="">
        </button>
        <strong class="col font-italic" id="voteAnswer{{ answer.id }}">
                {{ answer.total_likes }}
        </strong>
        <button type="submit"
                data-type="answer"
                data-action="down"
                data-id="{{ answer.id }}"
                class="col newVote btn-xs bg-light rounded">
            <img src="{% static 'images/caret-down.svg' %}" width="20" height="20" alt="">
        </button>
    </div>
{% endblock %}

app/articles/templates/articles/utils/likeDisPosts.html
{% block content %}
    {% load static %}
    <div class="col-4 mt-2 text-center">
        <button type="submit"
                data-type="post"
                data-action="up"
                data-id="{{ post.id }}"
                class="col newVote btn-xs bg-light rounded">
            <img src="{% static 'images/caret-up.svg' %}" width="20" height="20" alt="">
        </button>
        <strong class="col font-italic" id="votePost{{ post.id }}">
                {{ post.total_likes }}
        </strong>
        <button type="submit"
                data-type="post"
                data-action="down"
                data-id="{{ post.id }}"
                class="col newVote btn-xs bg-light rounded">
            <img src="{% static 'images/caret-down.svg' %}" width="20" height="20" alt="">
        </button>
    </div>
{% endblock %}

app/articles/templates/articles/utils/likeDisQuestions.html
{% block content %}
    {% load static %}
    <div class="col-4 mt-2 text-center">
        <button type="submit"
                data-type="post"
                data-action="up"
                data-id="{{ post.id }}"
                class="col newVote btn-xs bg-light rounded">
            <img src="{% static 'images/caret-up.svg' %}" width="20" height="20" alt="">
        </button>
        <strong class="col font-italic" id="votePost{{ post.id }}">
                {{ post.total_likes }}
        </strong>
        <button type="submit"
                data-type="post"
                data-action="down"
                data-id="{{ post.id }}"
                class="col newVote btn-xs bg-light rounded">
            <img src="{% static 'images/caret-down.svg' %}" width="20" height="20" alt="">
        </button>
    </div>
{% endblock %}

app/articles/templates/articles/utils/new_post.html
{% extends 'articles/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="text-center new_question my-1">
        <h3 class="font-italic">New post</h3>
    </div>
    <div class="card mt-3">
        <div class="card-body">
            {% if error %}
                <div class="alert alert-short alert-danger">{{ error }}</div>
            {% endif %}
            <form method="POST" action="{% url 'articles:new_post' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <script>
                    let post_type = document.getElementById('id_post_type_1')
                    if (post_type.value === 'lab') {

                    }

                </script>
                <div class="col ask_btn text-center">
                    <button class="btn btn-success" id="edit" type="submit">ASK</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

app/articles/templates/articles/utils/paginator.html
{% block content %}
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item {% if  not prev_url %}disabled{% endif %} }}">
                <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% for n in page_object.paginator.page_range %}
                {% if page_object.number == n %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
                    </li>
                {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            <li class="page-item {% if  not next_url %}disabled{% endif %} }}">
                <a class="page-link" href="{{ next_url }}" tabindex="-1" aria-disabled="true">Next</a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/articles/templates/articles/utils/post.html
{% extends 'articles/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">

{% block content %}
    <div class="card card_comment ">
        <div class="card-header">
            <div class="row">
                <h3 class="col-2">{{ post.author }}</h3>
                <p class="col-10 text-right"> {{ post.create_date }}</p>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="row col-3">
                    {% include 'articles/utils/likeDisPosts.html' %}
                    <div class="row col-7">
                        {% if post.author.avatar != '' %}
                            <img class="user_avatar card-img" src="{{ MEDIA_URL }}{{ post.author.avatar }}"
                             alt="no avatar">
                        {% else %}
                            <img class="user_avatar card-img" src="{% static 'avatars/default_avatar.svg' %}" alt="">
                        {% endif %}
                    </div>
                </div>
                <div class="col-9">
                    <h3 class="card-title text-center">{{ post.title }}</h3>
                    <p class=" text-break" style="max-width: 100%;">{{ post.text }}</p>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            Tags:
            {% if not post.tags.all %}
                None
            {% endif %}
            {% for tag in post.tags.all %}
                <a href="{% url 'articles:tags_list' tag.id %}">{{ tag.tag_name }}</a>
            {% endfor %}
        </div>
    </div>
    {% if page_object %}
        <h3 class="font-italic mt-3">Comments({{ post.total_comments }})</h3>
        {% for comment in page_object %}
            {% include 'articles/utils/comment.html' %}
        {% endfor %}
        {% if is_paginated %}
            {% include 'articles/utils/paginator.html' %}
        {% endif %}
    {% endif %}
    {% if request.user.is_anonymous %}
        <h3 class="font-italic my-3">Only registered users can add comments!</h3>
    {% else %}
        <div class="mt-3">
            <div class="text-center new_comment ">
                <h3 class="font-italic">Your Comment</h3>
            </div>
            <div class="card mb-5">
                <div class="card-body">
                    <form id="#example-form" method="POST" action="{% url 'articles:display_single' post.id %}">
                        {% csrf_token %}
                        {% if error %}
                            <div class="alert alert-short alert-danger">
                                {{ error }}
                            </div>
                        {% endif %}
                        {{ form|crispy }}
                        <div class="col OK_btn text-center">
                            <button class="btn btn-success" id="ans" type="submit">Comment</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

app/articles/templates/articles/utils/question.html
{% extends 'articles/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
<link rel="stylesheet" href="{% static 'css/question.css' %}">

{% block content %}
    <div class="card card_answer ">
        <div class="card-header">
            <div class="row">
                <h3 class="col-2">{{ question.author }}</h3>
                <p class="col-10 text-right"> {{ question.create_date }}</p>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="row col-3">
                    {% include 'articles/utils/likeDisQuestions.html' %}
                    <div class="row col-7">
                        {% if question.author.avatar != '' %}
                            <img class="user_avatar card-img" src="{% static question.author.avatar %}" alt="no avatar">
                        {% else %}
                            <img class="user_avatar card-img" src="{% static 'default_avatar.svg' %}" alt="">
                        {% endif %}
                    </div>
                </div>
                <div class="col-9">
                    <h3 class="card-title text-center">{{ question.title }}</h3>
                    <p class=" text-break" style="max-width: 100%;">{{ question.text }}</p>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            Tags:
            {% if not question.tags.all %}
                None
            {% endif %}
            {% for tag in question.tags.all %}
                <a href="{% url 'articles:tags_list' tag.id %}">{{ tag.tag_name }}</a>
            {% endfor %}
        </div>
    </div>
    {% if page_object %}
        <h3 class="font-italic mt-3">Answers({{ question.total_answers }})</h3>
        {% for answer in page_object %}
            {% include 'articles/utils/answer.html' %}
        {% endfor %}
        {% if is_paginated %}
            {% include 'articles/utils/paginator.html' %}
        {% endif %}
    {% endif %}
    {% if request.user.is_anonymous %}
        <h3 class="font-italic my-3">Only registered users can add answers!</h3>
    {% else %}
        <div class="mt-3">
            <div class="text-center new_answer ">
                <h3 class="font-italic">Your Answer</h3>
            </div>
            <div class="card mb-5">
                <div class="card-body">
                    <form method="POST" action="{% url 'articles:display_single' question.id %}">
                        {% csrf_token %}
                        {% if error %}
                            <div class="alert alert-danger">
                                {{ error }}
                            </div>
                        {% endif %}
                        {{ form|crispy }}
                        <div class="col OK_btn text-center">
                            <button class="btn btn-success" id="ans" type="submit">Answer</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

app/articles/templates/articles/utils/tags.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    <h3 class="font-italic mt-1">Posts with "{{ tag.tag_name }}" tag:</h3>
    {% for post in tag.posts.all %}
        {% include 'articles/utils/card.html' %}
    {% endfor %}
{% endblock %}