app/accounts/urls.py
from accounts import views
from django.urls import path

app_name = 'accounts'
urlpatterns = [

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registration/', views.registration_view, name='registration'),
    path('settings/', views.settings_view, name='settings'),

]

app/articles/urls.py
from django.urls import path
from articles import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'articles'
urlpatterns = [
	path('', views.index, name='10-ka Labs'),
	path('new_post/', views.new_post, name='new_post'),
	path('post/<int:post_id>', views.display_single, name='display_single'),
	path('get_posts/', views.get_posts, name='get_posts'),
	path('tags/<int:tag_id>', views.tags_list, name='tags_list'),
	path('ajax/vote/', views.vote, name="vote"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/config/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('labs/', include('labs.urls')),
    path('user/', include('accounts.urls')),
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
]

app/labs/urls.py
from django.urls import path
from labs import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'labs'
urlpatterns = [
    path('new_lab/', views.new_lab, name='new_lab'),
    path('labs_catalog/', views.labs_catalog, name='labs_catalog'),
    path('display_lab/<int:lab_id>', views.display_lab, name='display_lab'),
    path('task_status/<int:user_id>&<str:task_id>', views.task_status, name='task_status'),
    path('download/<str:path>', views.download, name='download')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/articles/models.py
from accounts.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone


class TagManager(models.Manager):
    def add_tags(self, tag):
        if Tag.objects.filter(tag_name=tag).exists():
            tag = self.get(tag_name=tag)
            tag.total += 1
            tag.save(update_fields=['total'])
        else:
            tag = self.create(tag_name=tag)
            tag.save()
        return tag


class Tag(models.Model):
    objects = TagManager()
    tag_name = models.TextField()
    total = models.IntegerField(default=1)

    def __str__(self):
        return self.tag_name


class LikeDislikeManager(models.Manager):
    def create_like_dislike(self, user, instance, object_id, action):
        try:
            like = self.filter(user=user).get(object_id=object_id)
            if like.beenPut and action == 'down':
                like.beenPut = False
                if instance.total_likes >= 1:
                    instance.total_likes -= 1
            elif not like.beenPut and action == 'up':
                like.beenPut = True
                instance.total_likes += 1
            like.save(update_fields=['beenPut'])
        except:
            like = self.create(user=user, obj=instance, object_id=instance.id)
            if action == 'up':
                like.beenPut = True
                instance.total_likes += 1
            like.save()

        instance.save(update_fields=['total_likes'])
        return like


class LikeDislike(models.Model):
    objects = LikeDislikeManager()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    beenPut = models.BooleanField(default=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    obj = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.user


class PostManager(models.Manager):
    def create_post(self, **kwargs):
        tags = kwargs['tags']
        post = self.create(author=kwargs.get('author'),
                           title=kwargs.get('title'), text=kwargs.get('text'),
                           is_pinned=kwargs.get('is_pinned'))
        post.save()
        for tag in tags:
            current_tag = Tag.objects.add_tags(tag)
            post.tags.add(current_tag)
        return post


class Post(models.Model):
    objects = PostManager()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')
    total_comments = models.IntegerField(default=0)
    total_likes = models.IntegerField(default=0)
    is_pinned = models.BooleanField(default=True)

    def publish(self):
        self.create_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class CommentManager(models.Manager):
    def create_comment(self, author, post, text):
        comment = self.create(author=author, post=post, text=text)
        post = Post.objects.get(id=post.id)
        post.total_comments += 1
        post.save(update_fields=['total_comments'])

        return comment


class Comment(models.Model):
    objects = CommentManager()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    total_likes = models.IntegerField(default=0)

    def publish(self):
        self.create_date = timezone.now()
        self.save()

    def __str__(self):
        return self.text

app/articles/forms.py
from django import forms


class PostForm(forms.Form):
    title = forms.CharField(label='Заголовок', max_length=255)
    text = forms.CharField(label='Текст', widget=forms.Textarea(attrs={'rows': '3'}))
    tags = forms.CharField(label="Тэги", required=False, max_length=50)
    pinned = forms.BooleanField(label="Закрепить", required=False)

    def clean_tags(self):
        tags = self.cleaned_data['tags']
        if tags:
            tags.split()
        return tags

    def clean_text(self):
        text = self.cleaned_data['text']
        return text

    def clean_title(self):
        title = self.cleaned_data['title']
        return title

    def clean_pinned(self):
        return self.cleaned_data['pinned']


class CommentForm(forms.Form):
    text = forms.CharField(label='Your comment', widget=forms.Textarea(attrs={'rows': '3'}))

    def clean(self):
        return self.cleaned_data

app/articles/views.py
import json

from articles.forms import PostForm, CommentForm
from articles.models import Post, Comment, Tag, LikeDislike
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404


def index(request: WSGIRequest):
    query_filter = None

    filters = request.GET.keys()
    if len(filters) == 1:
        query_filter = list(filters)[0]
    filter_map = {
        "popular": "-total_comments",
        "pinned": "-is_pinned",
    }

    sort_key = filter_map.get(query_filter, '-create_date')
    if sort_key == '-is_pinned':
        questions_list = Post.objects.all().filter(is_pinned=True).order_by('-create_date')
    else:
        questions_list = Post.objects.all().order_by(sort_key)
    question_context = paginate(questions_list, request, 5)
    question_context.update({'sort_key': sort_key})
    return render(request, 'articles/index.html', context=question_context)


def new_post(request):
    if request.method == 'GET':
        form = PostForm()
        if request.user.is_authenticated:
            return render(request, 'articles/utils/new_post.html', {'form': form})
        return redirect('accounts:login')
    else:
        if not request.user.is_authenticated:
            return HttpResponse(status=403)
        form = PostForm(request.POST)
        if not form.is_valid():
            return redirect(request.META['HTTP_REFERER'])
        tags = form.cleaned_data['tags'].split()
        post_full = Post.objects.create_post(author=request.user, title=form.cleaned_data['title'],
                                             text=form.cleaned_data['text'], is_pinned=form.cleaned_data['pinned'],
                                             tags=tags)
        if post_full:
            post_full.save()
            return redirect('../post/{}'.format(post_full.id))
        else:
            return render(request, 'articles/utils/new_post.html', {'error': 'Something went wrong. Please try again'})


def display_single(request, post_id):
    context = {}
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        form = CommentForm(request.POST)
        if not form.is_valid():
            context.update({'form': form})
        comment_full = Comment.objects.create_comment(author=request.user, post=post,
                                                      text=form.cleaned_data['text'])
        comment_full.save()
        return redirect('../post/{}'.format(post.id))
    comments = Comment.objects.filter(post=post_id).order_by('-create_date')
    comments_context = paginate(comments, request, 3)
    form = CommentForm()
    context.update({'form': form, 'post': post,
                    'page_object': comments_context['page_object'],
                    'is_paginated': comments_context['is_paginated'],
                    'next_url': comments_context['next_url'],
                    'prev_url': comments_context['prev_url']})
    return render(request, 'articles/utils/post.html', context=context)


def tags_list(request, tag_id):
    context = {}
    tag = get_object_or_404(Tag, id=tag_id)
    questions = Tag.objects.filter(id=tag_id)
    context.update({'questions': questions, 'tag': tag})
    return render(request, 'articles/utils/tags.html', context=context)


def paginate(objects_list, request, per_page):
    data_on_page = Paginator(objects_list, per_page)
    page_number = request.GET.get('page', 1)
    page = data_on_page.get_page(page_number)
    is_paginated = page.has_other_pages()
    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''
    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''
    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url,
    }
    return context


@login_required
def vote(request):
    post = request.POST
    user = request.user

    action = post['action']
    data_id = post['data_id']
    data_type = post['data_type']
    if data_type == 'post':
        data_object = Post.objects.get(pk=data_id)
    else:
        data_object = Comment.objects.get(pk=data_id)
    LikeDislike.objects.create_like_dislike(user, instance=data_object, object_id=data_id, action=action)

    return HttpResponse(data_object.total_likes, status=200)


@login_required
def get_posts(request: WSGIRequest):
    search = request.GET.get('search')
    page = request.GET.get('page')
    if search == '':
        return HttpResponse(status=200)
    if len(search) < 3:
        return HttpResponse('слишком короткий запрос (< 3 символов)', status=400)
    res = Post.objects.all().filter(title__icontains=search).order_by('-create_date')
    data = [{"id": res[i].id, "text": res[i].title} for i in range(len(res))]
    return HttpResponse(json.dumps({"results": data}), status=200)

app/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}10-ka Labs{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<nav class="navbar navbar-expand navbar-dark sticky-top">
    <div class="col-2">
        <a class="navbar-brand" href="{% url 'articles:10-ka Labs' %}">10-ka Labs</a>
    </div>
    <form class="col-4">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
    </form>
    {% if request.user.is_superuser %}
        <div class="col-4 row">
        <div class="dropdown col-6">
            <button class="btn btn-success btn-lg my-2 center-block dropdown-toggle" type="button"
                    id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Создать
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'articles:new_post' %}">Пост</a>
                <a class="dropdown-item" href="{% url 'labs:new_lab' %}">Лабораторную работу</a>
            </div>
        </div>
    {% else %}
        <div class="col-4 row">
    {% endif %}
    <div class="col-6">
        <a href="{% url 'labs:labs_catalog' %}">
            <button class="btn btn-success btn-lg my-2 center-block" type="submit">Каталог ЛР</button>
        </a>
    </div>
    </div>
    <div class="col-2">
        {% if request.user.is_anonymous %}
            <div class="row Login_and_Register">
                <div class="login col-8"><a href="{% url 'accounts:login' %}">Войти</a></div>
                <div class="Registration col-4"><a href="{% url 'accounts:registration' %}">Регистрация</a></div>
            </div>
        {% else %}
            <div class="row Logout_and_Settings">
            <div class="avatar col-7">
                {% if request.user.avatar != '' %}
                    <img class="user_avatar card-img" src="{{ MEDIA_URL }}{{ request.user.avatar }}"
                         alt="no avatar">
                {% else %}
                    <img class="user_avatar card-img" src="{% static 'avatars/default_avatar.svg' %}" alt="">
                {% endif %}
            </div>
            <div class="col-5">
                <div class="row">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="username">{{ request.user }}</span>
                        {#                        <img class="nav-settings" src="{% static 'images/settings.svg' %}" alt=""/>#}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'accounts:settings' %}">Профиль</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Выйти</a></li>
                    </ul>
                </div>
            </div>
        {% endif %}
        </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-9">
            {% block content %}
            {% endblock %}
        </div>
        <div class="col-3 my-5">
            <ul class="list-group">
                <li class="list-group-item d-flex">
                    <div>
                        <h3 class="font-italic">Популярные тэги</h3>
                        <ul class="row list-unstyled popular_tags">
                            {% for t in tags %}
                                <li class="active-link ml-3"><a
                                        href="{% url 'articles:tags_list' t.id %}">{{ t.tag_name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                </li>
                <li class="list-group-item d-flex">
                    <div>
                        <h3 class="font-italic">Активные пользователи</h3>
                        <ul class="list-unstyled">
                            {% for u in users %}
                                <li>{{ u.username }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script type="text/javascript" src="{% static "js/common.js" %}"></script>
{% block javascript %}
    {% if  user.is_authenticated %}
        <script type="text/javascript" src="{% static "js/LikeDislike.js" %}"></script>
        <script type="text/javascript" src="{% static "js/LabLoading.js" %}"></script>
    {% endif %}
{% endblock javascript %}

</body>
</html>

app/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}
{% block content %}
    <div class="nav_popular list-group-item rounded">
        <div class="nav nav-pills">
            <li class="col-4 btn-sm text-center">
                <a class="font-italic nav-link {% if sort_key == '-is_pinned' %} active {% endif %}"
                   href="?pinned"><strong>Закрепленное</strong></a>
            </li>
            <li class="col-4 btn-sm text-center">
                <a class="font-italic nav-link {% if sort_key == '-create_date' %} active {% endif %}"
                   href="{% url 'articles:10-ka Labs' %}"><strong>Новое</strong></a>
            </li>
            <li class="col-4 btn-sm text-center">
                <a class="font-italic nav-link {% if sort_key == '-total_comments' %} active {% endif %}"
                   href="?popular"><strong>Популярное</strong></a>
            </li>
        </div>
    </div>
    {% if page_object %}
        {% for post in page_object %}
            {% include 'articles/utils/card.html' %}
        {% endfor %}
        {% if is_paginated %}
            {% include 'articles/utils/paginator.html' %}
        {% endif %}
    {% else %}
        <h3 class="font-italic">Посты не найдены!</h3>
    {% endif %}
{% endblock %}