app/config/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('labs/', include('labs.urls')),
    path('user/', include('accounts.urls')),
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
]

app/labs/urls.py
from django.urls import path
from labs import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'labs'
urlpatterns = [
    path('new_lab/', views.new_lab, name='new_lab'),
    path('labs_catalog/', views.labs_catalog, name='labs_catalog'),
    path('display_lab/<int:lab_id>', views.display_lab, name='display_lab'),
    path('task_status/<int:user_id>&<str:task_id>', views.task_status, name='task_status'),
    path('download/<str:path>', views.download, name='download')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/labs/models.py
from django.db import models
from django.utils import timezone

from articles.models import Post
from accounts.models import User


class LabManager(models.Manager):
    def create_lab(self, author, title, description, executable, linked_post_id):
        return self.create(author=author,
                           title=title,
                           description=description,
                           linked_post=Post.objects.get(pk=linked_post_id) if linked_post_id is not None else None,
                           executable=executable)


class Lab(models.Model):
    objects = LabManager()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=512)
    executable = models.CharField(max_length=1024)
    correct_answer = models.CharField(max_length=1024)
    linked_post = models.ForeignKey(Post, on_delete=models.SET_NULL, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)

    def publish(self):
        self.create_date = timezone.now()
        self.save()

app/labs/forms.py
from django import forms


class LabForm(forms.Form):
    title = forms.CharField(label='Заголовок', max_length=255)
    description = forms.CharField(label='Описание', widget=forms.Textarea(attrs={'rows': '2'}), required=False)
    script = forms.CharField(label='Исполняемый скрипт', widget=forms.Textarea(attrs={'rows': '5'}), required=False)
    correct_answer = forms.CharField(label='Правильный ответ',
                                     help_text='{"answer": {"field1": "value1"}}',
                                     widget=forms.Textarea(attrs={'rows': '3'}), required=False)
    pinned = forms.BooleanField(label="Добавить ссылку на пост", required=False)
    linked_post = forms.IntegerField(disabled=True, required=False)

    def clean_pinned(self):
        return self.cleaned_data['pinned']

    def clean_correct_answer(self):
        return self.cleaned_data['correct_answer']

    def clean_description(self):
        return self.cleaned_data['description']

    def clean_title(self):
        return self.cleaned_data['title']

    def clean_linked_post(self):
        return self.cleaned_data['linked_post']

app/labs/views.py
import json
import os

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect

from labs.models import Lab
from labs.forms import LabForm
from labs.task_pool import TaskManager, Task

from config import settings

task_manager = TaskManager()


def new_lab(request):
    if request.method == 'GET':
        form = LabForm()
        if request.user.is_authenticated:
            return render(request, 'labs/utils/new_lab.html', {'form': form})
        return redirect('accounts:login')
    else:
        if not request.user.is_authenticated:
            return HttpResponse(status=403)
        form = LabForm(request.POST)
        if not form.is_valid():
            return redirect(request.META['HTTP_REFERER'])
        lab_full = Lab.objects.create_lab(author=request.user,
                                          title=form.cleaned_data['title'],
                                          description=form.cleaned_data['description'],
                                          executable=form.cleaned_data['script'],
                                          correct_answer=form.cleaned_data['correct_answer'],
                                          linked_post_id=form.cleaned_data['linked_post'])
        if lab_full:
            lab_full.save()
            return redirect('../labs_catalog')
        else:
            return render(request, 'labs/utils/new_lab.html', {'error': 'Something went wrong. Please try again'})


def labs_catalog(request):
    context = {}
    labs = Lab.objects.all().order_by('-create_date')
    context.update({'labs': labs})
    return render(request, 'labs/utils/labs_catalog.html', context=context)


def display_lab(request, lab_id):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    context = {}
    user = request.user
    task = task_manager.get_user_task(user_id=user.id)
    if task is not None:
        context.update({'error': 'Для пользователя уже запущено виртуальное окружение', 'task': task})
        return render(request, 'labs/utils/lab.html', context=context)
    lab = get_object_or_404(Lab, id=lab_id)
    task = task_manager.push_task(Task(user_id=user.id, executable=lab.executable))
    context.update({'status': 'ok', 'task': task})
    return render(request, 'labs/utils/lab.html', context=context)


def task_status(request, user_id, task_id):
    resp = task_manager.task_status(user_id, task_id)
    if resp['status'] is None:
        return HttpResponse(resp, status=404)
    return HttpResponse(json.dumps(resp), status=200)


@login_required
def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

app/labs/templates/labs/utils/dropdown_with_search.html
<div id="multi-select" style="display: none">
    <select class="js-example-basic-multiple col-3" name="states[]" multiple="multiple">
    </select>
</div>

app/labs/templates/labs/utils/lab.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if error %}
            <div class="alert alert-short alert-danger">
                {{ error }}
            </div>
        {% endif %}
        {% if status %}
            <div class="alert alert-short alert-success" role="alert">
                Загрузка виртуальной среды. Подождите...
            </div>
        {% endif %}
        <div class="card task-status my-5" id="{{ task.user_id }}_{{ task.id }}">
            <div class="card-body">
                <h5 class="card-title">Статус лабораторной работы</h5>
                <p id="lab-description" class="card-text">
                    Для подготовки виртуальной среды требуется некоторое время. Пожалуйста,
                    подождите...</p>
                <div id="lab-load-spin-{{ task.id }}" class="spinner-border" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
                <div id="vpn-conf-download" style="display: none">
                    <a href="#" class="btn btn-primary">Скачать VPN конфиг</a>
                </div>
                <div id="lab-stop" style="display: none">
                    <a href="#" class="btn btn-primary">Завершить ЛР</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/labs/templates/labs/utils/lab_card.html
{% load static %}


<div class="card mt-4">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ lab.linked_post.id }}"
                    aria-expanded="false" aria-controls="collapse{{ lab.id }}">
                {{ lab.title|truncatewords:100 }}
            </button>
        </h5>
    </div>

    <div id="collapse{{ lab.id }}" class="collapse show" aria-labelledby="headingOne"
         data-parent="#labs_catalog">
        <div class="card-body">
            <div>
              <span>
              {{ lab.description }}
          </span>
            </div>
            <form action='{% url 'labs:display_lab' lab.id %}' method='POST'>
                 {% csrf_token %}
                <button id="lab-load-btn-{{ lab.id }}" type="submit" class="btn btn-dark prepareLab mt-4">Приступить
                </button>
            </form>
        </div>
    </div>
</div>

app/labs/templates/labs/utils/labs_catalog.html
{% extends 'articles/base.html' %}

{% block content %}
<div id="labs_catalog">
    {% if labs %}
        <h3>Список лабораторных работ:</h3>
        {% for lab in labs %}
            {% include 'labs/utils/lab_card.html' %}
        {% endfor %}
    {% else %}
        <h3 class="font-italic">Лабораторные работы не найдены!</h3>
    {% endif %}
</div>
{% endblock %}

app/labs/templates/labs/utils/new_lab.html
{% extends 'articles/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <div class="text-center new_question my-1">
        <h3 class="font-italic">Новая лабораторная работа</h3>
    </div>
    <div class="card mt-3">
        <div class="card-body">
            {% if error %}
                <div class="alert alert-short alert-danger">{{ error }}</div>
            {% endif %}
            <form id="new_lab_form" method="POST" action="{% url 'labs:new_lab' %}">
                {% csrf_token %}
                {{ form|crispy }}
                {% include 'labs/utils/dropdown_with_search.html' %}
                <div class="col ask_btn text-center">
                    <button class="btn btn-success" id="new_lab_btn_save" type="button">Опубликовать</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}